Repository helpwave/services, pull requests merged in 2022-12, with the labels that each got.

#22 CODEOWNERS and other templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUST_TEMPLATE.md
Labels: chore

#19 bootstrap emergency room service
  libs/hwgorm/point.go
  services/emergency-room-svc/.env.example
  services/emergency-room-svc/README.md
  services/emergency-room-svc/api/v1.go
  services/emergency-room-svc/go.mod
  services/emergency-room-svc/go.sum
  services/emergency-room-svc/main.go
  services/emergency-room-svc/migrations/000001_init.down.sql
  services/emergency-room-svc/migrations/000001_init.up.sql
  services/emergency-room-svc/models/department.go
  services/emergency-room-svc/models/er.go
Labels: emergency-room-svc

#29 build: dynamically find services
  Makefile
Labels: chore

#31 build: add all target
  Makefile
Labels: chore

#32 Add ci for our monorepo setup
  .editorconfig
  .github/workflows/cicd-go.yaml
  .github/workflows/cicd.yaml
Labels: chore

#20 Add create ER handler
  services/emergency-room-svc/api/v1.go
  services/emergency-room-svc/main.go
Labels: emergency-room-svc

#34 ci: apply correct indent
  .github/workflows/cicd.yaml
Labels: bug, priority: high
