Repository helpwave/services, pull requests merged in 2023-07, with the labels that each got.

#242 chore: prefer but not require POSTGRES_DSN for database setup
  docker-run-migrations.sh
  infrastructure/README.md
  libs/hwgorm/go.mod
  libs/hwgorm/setup.go
  services/emergency-room-svc/main.go
  services/task-svc/main.go
  services/user-svc/main.go
Labels: chore, devops

#248 fix: some proto changes
  gen/dart/proto/services/task_svc/v1/room_svc.pb.dart
  gen/dart/proto/services/task_svc/v1/room_svc.pbjson.dart
  gen/dart/proto/services/task_svc/v1/ward_svc.pb.dart
  gen/dart/proto/services/task_svc/v1/ward_svc.pbjson.dart
  gen/go/proto/services/task_svc/v1/room_svc.pb.go
  gen/go/proto/services/task_svc/v1/ward_svc.pb.go
  gen/ts/proto/services/task_svc/v1/room_svc_pb.d.ts
  gen/ts/proto/services/task_svc/v1/room_svc_pb.js
  gen/ts/proto/services/task_svc/v1/ward_svc_pb.d.ts
  gen/ts/proto/services/task_svc/v1/ward_svc_pb.js
  libs/hwutil/parse.go
  proto/services/task_svc/v1/room_svc.proto
  proto/services/task_svc/v1/ward_svc.proto
  services/task-svc/internal/patient/models/models.go
  services/task-svc/internal/room/room.go
  services/task-svc/internal/ward/ward.go
Labels: chore

#252 infra: fix remote-build on fly
  .github/workflows/fly-deploy.yaml
  Dockerfile.standalone
  apisix/apisix.yaml
  infrastructure/README.md
  services/task-svc/fly.toml
  services/user-svc/fly.toml
Labels: infrastructure

#259 ci: remove deploy by image on Fly
  .github/workflows/fly-deploy.yaml
Labels: bug, devops

#260 ci: remove hard-coded organization name for Fly
  .github/workflows/cicd.yaml
  .github/workflows/fly-deploy.yaml
  services/auth-svc/fly.toml
Labels: devops

#265 fix: FLY_ORGANIZATION_NAME from secret to variable
  .github/workflows/cicd.yaml
Labels: bug

#266 fix: sometimes ... i love CIs
  .github/workflows/fly-deploy.yaml
Labels: bug

#262 feat: adopting Redis in Dapr
  .github/workflows/fly-deploy.yaml
  Dockerfile.apisix
  Dockerfile.standalone
  Procfile.standalone
  apisix/Procfile.apisix
  dapr/components/env-secret-store.yaml
  dapr/components/redis-pubsub.yaml
  dapr/config.yaml
  libs/common/grpc.go
  services/ory-svc/fly.toml
  services/task-svc/fly.toml
  services/user-svc/fly.toml
Labels: devops

#270 ci: fix reappeared bug with sed
  .github/workflows/fly-deploy.yaml
Labels: bug

#272 chore(deps): bump golang to 1.20
  Dockerfile.service
  Dockerfile.standalone
  libs/common/go.mod
  libs/hwgorm/go.mod
  libs/hwutil/go.mod
  libs/logging/go.mod
  libs/proto_helpers/go.mod
  services/auth-svc/go.mod
  services/auth-svc/go.sum
  services/emergency-room-svc/go.mod
  services/emergency-room-svc/go.sum
  services/ory-svc/go.mod
  services/ory-svc/go.sum
  services/task-svc/go.mod
  services/task-svc/go.sum
  services/user-svc/go.mod
  services/user-svc/go.sum
Labels: deps, devops

#279 fix(gorm): add explicit calls on uuid_generate_v4()
  services/task-svc/internal/bed/models/models.go
  services/task-svc/internal/patient/models/models.go
  services/task-svc/internal/room/models/models.go
  services/task-svc/internal/task-template/models/models.go
  services/task-svc/internal/task/models/models.go
  services/task-svc/internal/ward/models/models.go
  services/user-svc/internal/organization/organization.go
Labels: bug, devops, blocker
