Repository helpwave/services, pull requests merged in 2023-02, with the labels that each got.

#59 issue/50 organizations
  libs/common/keycloak.go
  libs/common/setup.go
  libs/hwutil/random.go
  services/user-svc/api/v1.go
  services/user-svc/main.go
Labels: user-svc

#60 infra: hibernate-gke and cf-dns via terraform
  .github/workflows/hibernate-gke.yaml
  kubernetes/iac/.terraform.lock.hcl
  kubernetes/iac/cloudflare.tf
  kubernetes/iac/gcp.tf
  kubernetes/iac/gke.tf
  kubernetes/iac/helm.tf
  kubernetes/iac/outputs.tf
  kubernetes/iac/providers.tf
  kubernetes/iac/variables.tf
  kubernetes/iac/versions.tf
Labels: chore

#62 issue/57 grpc
  Makefile
  images/service-preproc/Dockerfile
  images/service-preproc/Makefile
  images/service-preproc/run.sh
  libs/common/dapr.go
  libs/common/go.mod
  libs/common/go.sum
  libs/common/grpc.go
  libs/common/keycloak.go
  libs/common/setup.go
  libs/hwgorm/go.mod
  libs/hwgorm/go.sum
  libs/hwgorm/point.go
  libs/hwutil/parse.go
  libs/logging/go.mod
  libs/logging/go.sum
  libs/logging/util.go
  services/auth-svc/api/auth-svc.pb.go
  services/auth-svc/api/auth-svc.proto
  services/auth-svc/api/auth-svc_grpc.pb.go
  services/auth-svc/api/logging.go
  services/auth-svc/api/v1.go
  services/auth-svc/go.mod
  services/auth-svc/go.sum
  services/auth-svc/main.go
  services/emergency-room-svc/api/emergency-room-svc.pb.go
  services/emergency-room-svc/api/emergency-room-svc.proto
  services/emergency-room-svc/api/emergency-room-svc_grpc.pb.go
  services/emergency-room-svc/api/helpers.go
  services/emergency-room-svc/api/v1.go
  services/emergency-room-svc/go.mod
  services/emergency-room-svc/go.sum
  services/emergency-room-svc/main.go
  services/emergency-room-svc/models/department.go
  services/emergency-room-svc/models/er.go
  services/user-svc/api/logging.go
  services/user-svc/api/user-svc.pb.go
  services/user-svc/api/user-svc.proto
  services/user-svc/api/user-svc_grpc.pb.go
  services/user-svc/api/v1.go
  services/user-svc/go.mod
  services/user-svc/go.sum
  services/user-svc/main.go
Labels: enhancement, chore, priority: high

#63 infra: replace nginx with apisix
  kubernetes/iac/environments/local/.terraform.lock.hcl
  kubernetes/iac/environments/local/README.md
  kubernetes/iac/environments/local/main.tf
  kubernetes/iac/environments/local/providers.tf
  kubernetes/iac/environments/local/versions.tf
  kubernetes/iac/environments/staging/.terraform.lock.hcl
  kubernetes/iac/environments/staging/cloudflare.tf
  kubernetes/iac/environments/staging/gcp.tf
  kubernetes/iac/environments/staging/gke.tf
  kubernetes/iac/environments/staging/outputs.tf
  kubernetes/iac/environments/staging/providers.tf
  kubernetes/iac/environments/staging/variables.tf
  kubernetes/iac/environments/staging/versions.tf
  kubernetes/iac/helm.tf
  kubernetes/iac/modules/hw-tf-module-cluster-resources/.terraform.lock.hcl
  kubernetes/iac/modules/hw-tf-module-cluster-resources/apisix.tf
  kubernetes/iac/modules/hw-tf-module-cluster-resources/dapr.tf
  kubernetes/iac/modules/hw-tf-module-cluster-resources/variables.tf
  kubernetes/iac/modules/hw-tf-module-cluster-resources/versions.tf
Labels: chore

#67 feat(iac): sso subdomains
  kubernetes/iac/environments/staging/cloudflare.tf
  kubernetes/keycloak/helmfile.yaml
Labels: infrastructure

#74 feat(infra): setup APISIX to proxy gRPC traffic to Dapr
  kubernetes/iac/environments/local/.terraform.lock.hcl
  kubernetes/iac/environments/local/main.tf
  kubernetes/iac/environments/local/providers.tf
  kubernetes/iac/environments/local/versions.tf
  kubernetes/iac/environments/staging/.terraform.lock.hcl
  kubernetes/iac/environments/staging/cert.tf
  kubernetes/iac/environments/staging/cloudflare.tf
  kubernetes/iac/environments/staging/providers.tf
  kubernetes/iac/environments/staging/variables.tf
  kubernetes/iac/environments/staging/versions.tf
  kubernetes/iac/modules/hw-tf-module-cluster-resources/apisix.tf
  kubernetes/iac/modules/hw-tf-module-cluster-resources/cert-manager.tf
  kubernetes/iac/modules/hw-tf-module-cluster-resources/versions.tf
Labels: chore, infrastructure

#79 feat(task-svc): implement ward crud endpoints
  services/task-svc/api/helpers.go
  services/task-svc/api/ward-svc.pb.go
  services/task-svc/api/ward-svc.proto
  services/task-svc/api/ward-svc_grpc.pb.go
  services/task-svc/internal/ward/ward.go
  services/task-svc/migrations/000002_init.down.sql
  services/task-svc/migrations/000002_init.up.sql
Labels: enhancement, tasks-svc

#80 chore(common): use log level Error instead of Warn for logging middleware
  libs/common/grpc.go
Labels: chore
