Repository helpwave/services, pull requests merged in 2023-04, with the labels that each got.

#109 feat(infra): expose task-svc via gRPC-web
  infrastructure/terraform/modules/hw-tf-module-cluster-resources/apisix.tf
Labels: enhancement, APISIX

#111 fix: use correct protos
  .github/workflows/buf.yaml
  gen/proto/services/auth_svc/v1/auth_svc.pb.go
  gen/proto/services/auth_svc/v1/auth_svc_grpc.pb.go
  services/emergency-room-svc/main.go
  services/user-svc/main.go
Labels: bug

#117 chore: migrate to npmjs
  .github/workflows/publish-bufs.yaml
  gen/ts/.npmrc
Labels: chore

#115 dart package
  .gitattributes
  .github/workflows/publish-bufs.yaml
  gen/dart/.gitignore
  gen/dart/.pubignore
  gen/dart/LICENSE
  gen/dart/README.md
  gen/dart/pubspec.lock
  gen/dart/pubspec.yaml
Labels: chore

#118 fix: use gRPC-web instead of ts-proto
  buf.gen.yaml
  gen/ts/.npmignore
  gen/ts/package.json
  gen/ts/proto/libs/events/v1/user_events.ts
  gen/ts/proto/libs/events/v1/user_events_pb.d.ts
  gen/ts/proto/libs/events/v1/user_events_pb.js
  gen/ts/proto/services/auth_svc/v1/auth_svc.ts
  gen/ts/proto/services/auth_svc/v1/auth_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/auth_svc/v1/auth_svc_grpc_web_pb.js
  gen/ts/proto/services/auth_svc/v1/auth_svc_pb.d.ts
  gen/ts/proto/services/auth_svc/v1/auth_svc_pb.js
  gen/ts/proto/services/emergency_room_svc/v1/emergency_room_svc.ts
  gen/ts/proto/services/emergency_room_svc/v1/emergency_room_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/emergency_room_svc/v1/emergency_room_svc_grpc_web_pb.js
  gen/ts/proto/services/emergency_room_svc/v1/emergency_room_svc_pb.d.ts
  gen/ts/proto/services/emergency_room_svc/v1/emergency_room_svc_pb.js
  gen/ts/proto/services/task_svc/v1/patient_svc.ts
  gen/ts/proto/services/task_svc/v1/patient_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/task_svc/v1/patient_svc_grpc_web_pb.js
  gen/ts/proto/services/task_svc/v1/patient_svc_pb.d.ts
  gen/ts/proto/services/task_svc/v1/patient_svc_pb.js
  gen/ts/proto/services/task_svc/v1/room_svc.ts
  gen/ts/proto/services/task_svc/v1/room_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/task_svc/v1/room_svc_grpc_web_pb.js
  gen/ts/proto/services/task_svc/v1/room_svc_pb.d.ts
  gen/ts/proto/services/task_svc/v1/room_svc_pb.js
  gen/ts/proto/services/task_svc/v1/task_svc.ts
  gen/ts/proto/services/task_svc/v1/task_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/task_svc/v1/task_svc_grpc_web_pb.js
  gen/ts/proto/services/task_svc/v1/task_svc_pb.d.ts
  gen/ts/proto/services/task_svc/v1/task_svc_pb.js
  gen/ts/proto/services/task_svc/v1/ward_svc.ts
  gen/ts/proto/services/task_svc/v1/ward_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/task_svc/v1/ward_svc_grpc_web_pb.js
  gen/ts/proto/services/task_svc/v1/ward_svc_pb.d.ts
  gen/ts/proto/services/task_svc/v1/ward_svc_pb.js
  gen/ts/proto/services/user_svc/v1/user_svc.ts
  gen/ts/proto/services/user_svc/v1/user_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/user_svc/v1/user_svc_grpc_web_pb.js
  gen/ts/proto/services/user_svc/v1/user_svc_pb.d.ts
  gen/ts/proto/services/user_svc/v1/user_svc_pb.js
Labels: bug, chore

#119 fix(ci): publish buf when gen changed
  .github/workflows/publish-bufs.yaml
Labels: bug, chore

#121 fix: add package-json, was removed in migration
  gen/ts/package.json
Labels: bug, chore

#122 fix(ci): use PAT of github.com/helpwave-bot
  .github/workflows/publish-bufs.yaml
Labels: bug, chore

#123 fix(infra): set dapr-app-id header
  infrastructure/terraform/modules/hw-tf-module-cluster-resources/apisix.tf
Labels: bug, infrastructure

#126 chore: disarm versioning
  .github/workflows/buf.yaml
  .github/workflows/publish-bufs.yaml
  README.md
Labels: devops

#124 feat: bring organizations back home
  gen/dart/proto/services/user_svc/v1/organization_svc.pb.dart
  gen/dart/proto/services/user_svc/v1/organization_svc.pbenum.dart
  gen/dart/proto/services/user_svc/v1/organization_svc.pbjson.dart
  gen/dart/proto/services/user_svc/v1/organization_svc.pbserver.dart
  gen/dart/proto/services/user_svc/v1/user_svc.pb.dart
  gen/dart/proto/services/user_svc/v1/user_svc.pbjson.dart
  gen/dart/proto/services/user_svc/v1/user_svc.pbserver.dart
  gen/go/proto/services/user_svc/v1/logging.go
  gen/go/proto/services/user_svc/v1/organization_svc.pb.go
  gen/go/proto/services/user_svc/v1/organization_svc_grpc.pb.go
  gen/go/proto/services/user_svc/v1/user_svc.pb.go
  gen/go/proto/services/user_svc/v1/user_svc_grpc.pb.go
  gen/ts/proto/services/user_svc/v1/organization_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/user_svc/v1/organization_svc_grpc_web_pb.js
  gen/ts/proto/services/user_svc/v1/organization_svc_pb.d.ts
  gen/ts/proto/services/user_svc/v1/organization_svc_pb.js
  gen/ts/proto/services/user_svc/v1/user_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/user_svc/v1/user_svc_grpc_web_pb.js
  gen/ts/proto/services/user_svc/v1/user_svc_pb.d.ts
  gen/ts/proto/services/user_svc/v1/user_svc_pb.js
  proto/services/user_svc/v1/organization_svc.proto
  proto/services/user_svc/v1/user_svc.proto
  services/user-svc/go.mod
  services/user-svc/go.sum
  services/user-svc/internal/organization/organization.go
  services/user-svc/internal/user/user.go
  services/user-svc/main.go
  services/user-svc/migrations/000001_init.down.sql
  services/user-svc/migrations/000001_init.up.sql
Labels: enhancement, ADR-005: SSO

#128 chore: changes to republish the packages
  gen/dart/proto/services/user_svc/v1/user_svc.pb.dart
  gen/dart/proto/services/user_svc/v1/user_svc.pbjson.dart
  gen/dart/proto/services/user_svc/v1/user_svc.pbserver.dart
  gen/go/proto/services/user_svc/v1/user_svc.pb.go
  gen/go/proto/services/user_svc/v1/user_svc_grpc.pb.go
  gen/ts/proto/services/user_svc/v1/user_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/user_svc/v1/user_svc_grpc_web_pb.js
  gen/ts/proto/services/user_svc/v1/user_svc_pb.d.ts
  gen/ts/proto/services/user_svc/v1/user_svc_pb.js
  proto/services/user_svc/v1/user_svc.proto
Labels: chore

#135 feat: mock organization members
  gen/dart/proto/services/user_svc/v1/organization_svc.pb.dart
  gen/dart/proto/services/user_svc/v1/organization_svc.pbjson.dart
  gen/dart/proto/services/user_svc/v1/organization_svc.pbserver.dart
  gen/go/proto/services/user_svc/v1/organization_svc.pb.go
  gen/go/proto/services/user_svc/v1/organization_svc_grpc.pb.go
  gen/ts/proto/services/user_svc/v1/organization_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/user_svc/v1/organization_svc_grpc_web_pb.js
  gen/ts/proto/services/user_svc/v1/organization_svc_pb.d.ts
  gen/ts/proto/services/user_svc/v1/organization_svc_pb.js
  proto/services/user_svc/v1/organization_svc.proto
  services/user-svc/internal/organization/organization.go
Labels: enhancement, user-svc

#137 fix(ci): prevent ci loop
  .github/workflows/publish-bufs.yaml
  gen/dart/proto/services/user_svc/v1/organization_svc.pb.dart
  gen/dart/proto/services/user_svc/v1/organization_svc.pbjson.dart
  gen/dart/pubspec.yaml
  gen/go/proto/services/user_svc/v1/organization_svc.pb.go
  gen/ts/package.json
  gen/ts/proto/services/user_svc/v1/organization_svc_pb.d.ts
  gen/ts/proto/services/user_svc/v1/organization_svc_pb.js
  proto/services/user_svc/v1/organization_svc.proto
  services/user-svc/internal/organization/organization.go
Labels: bug

#138 fix(ci): race condition
  .github/workflows/publish-bufs.yaml
  gen/dart/proto/services/user_svc/v1/user_svc.pb.dart
  gen/dart/proto/services/user_svc/v1/user_svc.pbjson.dart
  gen/dart/proto/services/user_svc/v1/user_svc.pbserver.dart
  gen/dart/pubspec.yaml
  gen/go/proto/services/user_svc/v1/user_svc.pb.go
  gen/go/proto/services/user_svc/v1/user_svc_grpc.pb.go
  gen/ts/proto/services/user_svc/v1/user_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/user_svc/v1/user_svc_grpc_web_pb.js
  gen/ts/proto/services/user_svc/v1/user_svc_pb.d.ts
  gen/ts/proto/services/user_svc/v1/user_svc_pb.js
  proto/services/user_svc/v1/user_svc.proto
Labels: bug, enhancement

#139 feat: replace Keycloak with generic OIDC provider
  gen/dart/proto/services/auth_svc/v1/auth_svc.pb.dart
  gen/dart/proto/services/auth_svc/v1/auth_svc.pbjson.dart
  gen/dart/proto/services/auth_svc/v1/auth_svc.pbserver.dart
  gen/go/proto/services/auth_svc/v1/auth_svc.pb.go
  gen/go/proto/services/auth_svc/v1/auth_svc_grpc.pb.go
  gen/go/proto/services/auth_svc/v1/logging.go
  gen/ts/proto/services/auth_svc/v1/auth_svc_grpc_web_pb.d.ts
  gen/ts/proto/services/auth_svc/v1/auth_svc_grpc_web_pb.js
  gen/ts/proto/services/auth_svc/v1/auth_svc_pb.d.ts
  gen/ts/proto/services/auth_svc/v1/auth_svc_pb.js
  libs/common/auth.go
  libs/common/go.mod
  libs/common/grpc.go
  libs/common/keycloak.go
  libs/common/setup.go
  proto/services/auth_svc/v1/auth_svc.proto
  services/auth-svc/.env.example
  services/auth-svc/TokenResponse.html
  services/auth-svc/go.mod
  services/auth-svc/main.go
  services/ory-svc/.env.example
  services/task-svc/.env.example
  services/task-svc/main.go
  services/user-svc/.env.example
Labels: enhancement, ADR-005: SSO

#143 fix(ci): checkout fresh main for ci
  .github/workflows/publish-bufs.yaml
  gen/dart/pubspec.yaml
Labels: chore, devops
